export type BlogPost = {
  slug: string;
  title: string;
  date: string; // keep as display string to stay simple
  summary?: string;
  content: string[]; // paragraphs
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "im-betting-my-life-on-this",
    title: "I'm betting my life on this",
    date: "2026-01-28",
    summary: "A personal essay on what I want to spend my professional life doing and why.",
    content: [
      "This is a short personal essay on what I want to spend my professional life doing and why.",
      "There are four core ideas:",
      "1.Success without luck as a non-outlier",
      "2.The rise of the Asian-American diaspora",
      "3.The intersection of tech and finance",
      "4.The bipolar world between China and America",
      "### Introduction",
      "Realistically there are only a few ways to achieve (100 M+) at a young age:",
      "-Startup founder",
      "-Influencer",
      "-Elite athlete",
      "-Marry a heiress",
      "-Outperform markets consistently over a long period",
      "Unfortunately for all of these, the skillset required to increase your chances from near zero to worth pursuing are extremely rare.",
      "It isn't easy to admit, but I'm too normal to have an asymmetric advantage in any of these.",
      "### But I've met non-outliers who've gotten wealthy without getting too lucky.",
      "They all positioned themselves to be the right person in the right place at the right time building a business that someone has already built before.",
      "This is nowhere near easy, but identifying the right place is not impossible, neither is figuring out the right time.",
      "Being the right person and building a business is also not easy, but I'm a capable person willing to work really hard, I just need the odds to be better than near zero.",
      "### I think I know the right place",
      "As a UWaterloo CS + finance student I'm surrounded by a group of people whom I'm sure is going to be the most successful demographic of the next 20 years:",
      "Second-generation Asian-Americans/Canadians in tech",
      "They are:",
      "-Intelligent",
      "-Humble",
      "-Hard working",
      "-Born in a middle-class family that values education and financial responsibility",
      "-Dislikes losing face (High standards for their work)",
      "-Seeks prestige",
      "-Seeks stability",
      "-Still identifies with the immigrants desire to prove themselves",
      "-Perfectly fluent in english and fully integrated in western society",
      "Willing to adopt what makes the western world so successful",
      "  -Initiative",
      "  -Confidence",
      "  -Winner takes all mentality",
      "The average of this group will go on the make high salaries in tech, the above average will join elite tech companies, and the elite will become top-tier founders.",
      "I see this with my own eyes at Waterloo. Hundreds shipped off to top tech and quant companies in America with the best and most ambitious dropping out to create startups.",
      "By 30 many will be millionaires and the best will become billionaires.",
      "I entered Waterloo with the mentality that I needed to outperform my classmates. I quickly realized it's a lot better to build a career on my classmates outperforming the world.",
      "### I think I know the right time",
      "When a demographic becomes successful or \"nouveau riche\", there are many opportunities to build businesses offering services to them in a style that aligns with their specific needs.",
      "Think of the old rich European families or the American industrial elite. All the high-profile services they need, they already have, offered by someone they already know.",
      "-Lawyers",
      "-Accountants",
      "-Real estate managers",
      "-Doctors",
      "-Security",
      "-Personal Trainers",
      "-Household management",
      "You need to be both relatable and have connections within the circle. Otherwise it's impossible to break in. An Asian-Canadian kid like me has no chance… Unless Asian-Canadians are next up.",
      "If you agree with me, then the next decade is the prime time to enter this field. There are very little businesses targeting this group of people.",
      "Even the \"mere\" millionaires will need wealth advisors and accountants while the future billionaires will need the entire suite.",
      "The best part is that while businesses are hard, the difference between a business and a startup is precedent. You're doing something someone already did just for a different group of people.",
      "### I think I'm the right person",
      "I think you need to be:",
      "-Great at intimate networking",
      "-Willing to approach people humbly",
      "-A deep critical thinker",
      "-Above average in both IQ and EQ",
      "-Genuinely well-intentioned",
      "-Multidisiciplinary",
      "And most importantly",
      "-Be respected",
      "-Be relatable",
      "-Have tons of opportunities to network with future clients and team members",
      "I'm not all of these, but I'm most of these, and I think I can fix the ones I'm not.",
      "### Tech + Finance",
      "Being at Waterloo is like being at the spawn point. Everyone I meet, in my year, the years above, or the years below, more than likely falls into the category of people I have been describing. I realized (fortunately after I already got in) that to meet these people you need to be in tech.",
      "Being a SWE also has other advantages. For one, it's a great fallback if this bet fails. But the main benefit is really the ability to be places tech people are and understand how they're feeling.",
      "I've been able to network in Waterloo, Toronto, China, and soon SF all because I'm in tech.",
      "I don't know if this is a fair statement, but I also feel like it's easier to be respected by tech people when you're also in tech.",
      "My end objective is to be known by tech people as the finance person. The person they have in their mind as someone worth having a chat about years down the line.",
      "Being in finance also has immense value in my opinion. Finance is a different art from CS and there isn't much overlap. Most tech people don't get finance and most finance people don't get tech.",
      "Yet it's such an integral part of any young ambitious person's life and there are talented people on both sides that never get a chance to meet.",
      "Eventually the goal is to build a strong enough network that when I do have a desire to start a family office or something similar I'll have ample connections on both sides.",
      "### The China Continuation",
      "If this goes well, I'll already be doing pretty good, but I see an area that could push this from family office → multinational financial corporation",
      "It's pretty obvious to me that for the next half century it will be America one, China two. I don't see China overtaking America and I don't see anyone else overtaking China.",
      "But China will never fully escape the influence of America and America will never be able to suppress China. They will need to find a way to live in a bipolar world.",
      "1.Chinese companies/startups need American money",
      "2.Wealthy Americans need to diversify into China",
      "3.Wealthy Chinese really want to get money into America",
      "4.American companies want access to the Chinese market",
      "5.Chinese companies want access to the American market",
      "Basically both sides need people that understand the other side deeply.",
      "I hope to understand China a lot more than most Americans and I hope understand America a lot more than most Chinese.",
      "This is a lifelong journey and I'm not going to try and predict anything, but I'm going to give it my all.",
    ],
  },
];
